In [ ]:
#Question1
import numpy as np
n= int(input())
m= int(input())
arr1 = np.array([None]*n)
arr2 = np.array([None]*m)

for i in range(n):
  x= int(input())
  arr1[i] = x
for i in range(m):
  x= int(input())
  arr2[i] = x
c=0
for i in range(len(arr1)):

  for j in range(len(arr2)):
    if arr1[i] == arr2[j]:
      c+=1

print("output",len(arr1)+len(arr2)-c)

KeyboardInterrupt: ignored

In [ ]:
import numpy as np



In [ ]:
#question2
arr =[-5, 7, -3, -4, 9, 10, -1, 11]
c=0
n= len(arr)
new = np.array([None]*n)
for i in range(len(arr)):
  if arr[i] < 0:
    c+=1
idx=0
x=0
for i in range(len(arr)):

  if arr[i] < 0:

    new[(n-c)+idx] =arr[i]


    idx+=1
  else:
    new[x] =arr[i]
    x+=1
print(new)

[7 9 10 11 -5 -3 -4 -1]


In [ ]:
#question 3
N = 5
S = 12
A = [1,2,3,7,5]
for i in range(N):
  sum=A[i]

  for j in range(i+1,N,1):
    sum+= A[j]
   # idx=
    if sum == S:

      y= j

      break
  if sum == S:
   x= i
   break
print(x+1,y+1) #as output position starts from 1



In [ ]:
########################
arr=np.array([3,1,4,5,1,2,6])
s=0
e=0
for  i in range(len(arr)):
  for j in range(i+i,len(arr)):
    if arr[i] == arr[j]:
      s=i
      e=j
      break
temp=arr[e]
for i in range(e-1,s-1,-1):
  arr[i+1] = arr[i]
arr[s]=7
print(s,e)
print(arr)

1 4
[3 7 1 4 5 2 6]


In [ ]:
#question4
N = 5
arr = [1, 1, 1, 1, 1]
X = 1
c=0
for i in range(N):
  if arr[i] == X:
    c+=1
print(c)

5


In [ ]:
arr=np.array([3,1,4,5,8,2,21,56,-5,9])

for i in range(len(arr)-1):
  for j in range(i+1,len(arr),1):
    if arr[i] > arr[j]:

      arr[i],arr[j] =arr[j],arr[i]


print(arr)


3 1
1 3
1 -5
-5 1
3 2
2 3
2 1
1 2
4 3
3 4
3 2
2 3
5 4
4 5
4 3
3 4
8 5
5 8
5 4
4 5
8 5
5 8
21 8
8 21
56 21
21 56
21 9
9 21
56 21
21 56
[-5  1  2  3  4  5  8  9 21 56]


rough


In [13]:
import numpy as np
rslt= np.zeros(50,dtype=int)
arr =np.array([1,3,1,1,2,2,2,1])
# count=1
# idx=0
# for i in range(len(arr)):
#   if arr[i]==arr[i+1]:
#     count +=1
#     continue
#   else:
#     rslt[idx]= count
#     rslt[idx+1]=arr[i]
#     idx+=2

#   count=1

# print(rslt)
i=0
j=0
count=0
while i < len(arr):
  rslt[j+1] = arr[i]
  k=arr[i]
  while i< len(arr):
    if arr[i]==k:
      count+=1
      i+=1
    else:
      break
  rslt[j]=count
  j+=2
  count=0
print(rslt)








[1 1 1 3 2 1 3 2 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
